console.log(Math.abs(-4))
console.log(Math.PI)
console.log(Math.LN10)
console.log(Math.ceil(3.5))
console.log(Math.floor(24.4))
console.log(Math.random())
console.log(Math.floor(Math.random()*10)+1)
// console.log(Math.)
// console.log(Math.)